import Head from 'next/head'
import Footer from '../components/footer'
import styles from '../styles/Home.module.css'
import {ThemeProvider} from '../components/theme'
import Change from '../components/theme'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TOP | NT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/kazu8901">MyApp</a>
        </h1>
        <ThemeProvider>
          <Change />
        </ThemeProvider>
      </main>

      <Footer/>
    </div>
  )
}
